#[derive(Copy, Clone, Eq, PartialEq)]
pub enum Symbol {
    Add,
    Sub,
    Mul,
    Div,
    Rem,
    Increment,
    Decrement,
    Power,
    Root,
    BitNot,
    BitAnd,
    BitXor,
    BitOr,
    Equal,
    NotEqual,
    Less,
    LessOrEqual,
    Greater,
    GreaterOrEqual,
    Not,
    And,
    Or,
    Create,
    Assign,
    AddAssign,
    SubAssign,
    MulAssign,
    DivAssign,
    RemAssign,
    ChangeMin,
    ChangeMax,
    Exchange,
    OpenBracket,
    CloseBracket,
    OpenBrace,
    CloseBrace,
    Comma,
    End,
}

impl Symbol {
    pub fn to_str(&self) -> &str {
        match self {
            Symbol::Add => "+",
            Symbol::Sub => "-",
            Symbol::Mul => "*",
            Symbol::Div => "/",
            Symbol::Rem => "%",
            Symbol::Increment => "++",
            Symbol::Decrement => "--",
            Symbol::Power => "**",
            Symbol::Root => "//",
            Symbol::BitNot => "~",
            Symbol::BitAnd => "&",
            Symbol::BitXor => "^",
            Symbol::BitOr => "|",
            Symbol::Equal => "==",
            Symbol::NotEqual => "!=",
            Symbol::Less => "<",
            Symbol::LessOrEqual => "<==",
            Symbol::Greater => ">",
            Symbol::GreaterOrEqual => ">==",
            Symbol::Not => "!",
            Symbol::And => "&&",
            Symbol::Or => "||",
            Symbol::Create => ":=",
            Symbol::Assign => "=",
            Symbol::AddAssign => "+=",
            Symbol::SubAssign => "-=",
            Symbol::MulAssign => "*=",
            Symbol::DivAssign => "/=",
            Symbol::RemAssign => "%=",
            Symbol::ChangeMin => "<=",
            Symbol::ChangeMax => ">=",
            Symbol::Exchange => "<=>",
            Symbol::OpenBracket => "(",
            Symbol::CloseBracket => ")",
            Symbol::OpenBrace => "{",
            Symbol::CloseBrace => "}",
            Symbol::Comma => ",",
            Symbol::End => ";",
        }
    }

    pub fn get_len_order_list() -> Vec<Symbol> {
        vec![
            Symbol::LessOrEqual,
            Symbol::GreaterOrEqual,
            Symbol::Exchange,
            Symbol::Increment,
            Symbol::Decrement,
            Symbol::Power,
            Symbol::Root,
            Symbol::Equal,
            Symbol::NotEqual,
            Symbol::And,
            Symbol::Or,
            Symbol::Create,
            Symbol::AddAssign,
            Symbol::SubAssign,
            Symbol::MulAssign,
            Symbol::DivAssign,
            Symbol::RemAssign,
            Symbol::ChangeMin,
            Symbol::ChangeMax,
            Symbol::Add,
            Symbol::Sub,
            Symbol::Mul,
            Symbol::Div,
            Symbol::Rem,
            Symbol::BitNot,
            Symbol::BitAnd,
            Symbol::BitXor,
            Symbol::BitOr,
            Symbol::Less,
            Symbol::Greater,
            Symbol::Not,
            Symbol::Assign,
            Symbol::OpenBracket,
            Symbol::CloseBracket,
            Symbol::OpenBrace,
            Symbol::CloseBrace,
            Symbol::Comma,
            Symbol::End,
        ]
    }

    pub fn get_reserved_char_list() -> Vec<char> {
        vec!['+', '-', '*', '/', '%', '=', '!', '<', '>', ':', ',', ';', '(', ')', '{', '}']
    }
}